### ISSUE TITLE
Class Drupal\paragraphs\Entity\Paragraph does not exist

### ISSUE THREAD

**Issue by kubakadzielawa** [dennisinteractive/behat-drupal-paragraphs#2]
I'm using Drupal 8.7.6 and I have almost hundred Behat tests and everything works great. My problem is with more advanced tests which contains paragraphs. I started using ready contexts: https://github.com/dennisinteractive/behat-drupal-paragraphs

It is my behat-base.yml configuration

````
default:
  autoload:
    '': %paths.base%/bootstrap
  suites:
    default:
      drush: 'drush'
      paths: [ %paths.base%/features ]
      filters:
        tags: ~@wip&&~@broken
      contexts:
        - DennisDigital\Behat\Drupal\Paragraphs\Context\ParagraphsContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
  extensions:
    DMore\ChromeExtension\Behat\ServiceContainer\ChromeExtension: ~
    Behat\MinkExtension:
      base_url: "http://nginx:8080"
      files_path: %paths.base%/data-files
      sessions:
        default:
          chrome:
            api_url: "http://chrome:9222"
    Drupal\DrupalExtension:
      blackbox: ~
      api_driver: 'drush'
      drush:
        alias: 'self'
        root: %paths.base%/web
````

I wrote tests based on that configuration and I'm getting an error

>   Class Drupal\paragraphs\Entity\Paragraph does not exist

Here is my scenario:

   ````
@api
  Scenario: Create an article and add paragraphs
    Given "article" content:
      | title | status |
      | Test  | 1      |
    Given I add the following paragraph to field "field_paragraphs":
      | paragraph_field | value     |
      | type            | text      |
      | field_text      | Some text |
````

Do you know why I'm getting that error?
